---
title: Spokenjagers
hero_image: images/ghostbusters.png
description: Maak een spel over het vangen van spoken!
listed: true
copyedit: true
version: 4.1.0
last_tested: 2018-11-01
steps:
  - 
    title: Inleiding
  - 
    title: Een spook laten bewegen
  - 
    title: Willekeurige spoken
    completion:
      - engaged
  - 
    title: Code for catching ghosts
  - 
    title: Add a score
  - 
    title: Add a timer
    completion:
      - internal
  - 
    title: Challenge
    challenge: true
    completion:
      - external
  - 
    title: What can you do now?
