---
title: घोस्टबस्टर्स
hero_image: images/ghostbusters.png
description: भूत पकड़ने वाला गेम बनाएँ!
listed: true
copyedit: true
version: 4.1.0
last_tested: 2018-11-01
steps:
  - 
    title: भूमिका
  - 
    title: भूत का एनिमेशन बनाना
  - 
    title: अस्थाई भूत
  - 
    title: 'चुनौती: अधिक अस्थाई'
    challenge: true
  - 
    title: भूत पकड़ने के लिए कोड
  - 
    title: 'चुनौती: ध्वनि जोड़ें'
    challenge: true
  - 
    title: स्कोर जोड़ें
  - 
    title: टाइमर(timer) जोड़ना
  - 
    title: 'चुनौती: और स्प्रिट्स'
    challenge: true
  - 
    title: आगे क्या?
