---
title: Caça Fantasmas
hero_image: images/ghostbusters.png
description: Faz um jogo em que capturas fantasmas!
listed: true
copyedit: true
version: 4.1.0
last_tested: 2018-11-01
steps:
  - 
    title: Introdução
  - 
    title: Animar um fantasma
  - 
    title: Fantasmas aleatórios
    completion:
      - engaged
  - 
    title: 'Desafio: mais aleatoriedade'
    challenge: true
  - 
    title: Código para capturar fantasmas
  - 
    title: 'Desafio: adiciona um som'
    challenge: true
  - 
    title: Adiciona uma pontuação
  - 
    title: Adiciona um temporizador
    completion:
      - internal
  - 
    title: 'Desafio: Mais atores'
    challenge: true
  - 
    title: O que se segue?
