---
title: Caça Fantasmas
hero_image: images/ghostbusters.png
description: Faz um jogo em que capturas fantasmas!
listed: true
copyedit: true
version: 4.1.0
last_tested: 2018-11-01
steps:
  - 
    title: Introdução
  - 
    title: Animar um fantasma
  - 
    title: Fantasmas aleatórios
    completion:
      - engaged
  - 
    title: Code for catching ghosts
  - 
    title: Add a score
  - 
    title: Add a timer
    completion:
      - internal
  - 
    title: Challenge
    challenge: true
    completion:
      - external
  - 
    title: What can you do now?
