---
title: Cazafantasmas
hero_image: images/ghostbusters.png
description: "¡Haz un juego sobre atrapar fantasmas!"
listed: true
copyedit: true
version: 4.1.0
last_tested: 2018-11-01
steps:
- title: Introducción
  completion: engaged
- title: Animando un fantasma
- title: Fantasmas aleatorios
- title: 'Desafío: más aleatoriedad'
  challenge: true
- title: Código para atrapar fantasmas
- title: 'Desafío: añadir un sonido'
  challenge: true
- title: Añadir una puntuación
  completion: internal
- title: Añadir un temporizador
- title: 'Desafío: más objetos'
  challenge: true
- title: "¿Qué sigue?"
