---
title: Dal ysbrydion
hero_image: images/ghostbusters.png
description: Creu gêm i ddal ysbrydion!
listed: true
copyedit: true
version: 4.1.0
last_tested: 2018-11-01
steps:
- title: Cyflwyniad
- title: Animeiddio ysbryd
- title: Ysbrydion ar hap
  completion:
  - engaged
- title: 'Her: mwy o bethau ar hap'
  challenge: true
- title: Côd i ddal ysbrydion
- title: 'Her: ychwanegu sain'
  challenge: true
- title: Ychwanegu sgôr
- title: Ychwanegu Amserydd
  completion:
  - internal
- title: 'Her: mwy o gorluniau'
  challenge: true
- title: Profwch eich hun
- title: Beth nesaf?
