---
title: Dal ysbrydion
hero_image: images/ghostbusters.png
description: Creu gêm i ddal ysbrydion!
listed: true
copyedit: true
version: 4.1.0
last_tested: 2018-11-01
steps:
  - 
    title: Cyflwyniad
  - 
    title: Animeiddio ysbryd
  - 
    title: Ysbrydion ar hap
    completion:
      - engaged
  - 
    title: Code for catching ghosts
  - 
    title: Add a score
  - 
    title: Add a timer
    completion:
      - internal
  - 
    title: Challenge
    challenge: true
    completion:
      - external
  - 
    title: What can you do now?
