---
title: Geisterjäger
hero_image: images/ghostbusters.png
description: Mache ein Spiel über Gespensterjagd!
listed: true
copyedit: true
version: 4.1.0
last_tested: 2018-11-01
steps:
  - 
    title: Einleitung
  - 
    title: Animiere ein Gespenst
  - 
    title: Zufällige Orte
    completion:
      - engaged
  - 
    title: 'Herausforderung: Mehr Zufälligkeit'
    challenge: true
  - 
    title: Code für eine Geisterjagd
  - 
    title: 'Herausforderung: Ein Geräusch hinzufügen'
    challenge: true
  - 
    title: Eine Punktzahl hinzufügen
  - 
    title: Eine Stoppuhr hinzufügen
    completion:
      - internal
  - 
    title: 'Herausforderung: Mehr Figuren'
    challenge: true
  - 
    title: What next?
