---
title: Vânătorii de fantome
hero_image: images/ghostbusters.png
description: Creează un joc despre prinderea fantomelor!
listed: true
copyedit: true
version: 4.1.0
last_tested: 2018-01-01
steps:
  - 
    title: Introducere
  - 
    title: Animează o fantomă
  - 
    title: Fantome la întâmplare
    completion:
      - engaged
  - 
    title: Code for catching ghosts
  - 
    title: Add a score
  - 
    title: Add a timer
    completion:
      - internal
  - 
    title: Challenge
    challenge: true
    completion:
      - external
  - 
    title: What can you do now?
