---
title: Caça-fantasmas
hero_image: images/ghostbusters.png
description: Criar um jogo de caça-fantasmas!
listed: true
copyedit: true
version: 4.1.0
last_tested: 01-11-2018
steps:
- title: Introdução
  completion: engaged
- title: Animando um fantasma
- title: Fantasmas aleatórios
- title: 'Desafio: mais aleatoriedade'
  challenge: true
- title: Código para capturar fantasmas
- title: 'Desafio: adicionar um som'
  challenge: true
- title: Adicionar uma pontuação
  completion: internal
- title: Adicionar um cronômetro
- title: 'Desafio: mais fantasmas'
  challenge: true
- title: E agora?
