---
title: Caça-fantasmas
hero_image: images/ghostbusters.png
description: Criar um jogo de caça-fantasmas!
listed: true
copyedit: true
version: 4.1.0
last_tested: 01-11-2018
steps:
  - 
    title: Introdução
  - 
    title: Animando um fantasma
  - 
    title: Fantasmas aleatórios
    completion:
      - engaged
  - 
    title: 'Desafio: mais aleatoriedade'
    challenge: true
  - 
    title: Código para capturar fantasmas
  - 
    title: 'Desafio: adicionar um som'
    challenge: true
  - 
    title: Adicionar uma pontuação
  - 
    title: Adicionar um cronômetro
    completion:
      - internal
  - 
    title: 'Desafio: Mais fantasmas'
    challenge: true
  - 
    title: O que se segue?
