---
title: Ghostbusters
hero_image: images/ghostbusters.png
description: Buat game tentang menangkap hantu!
listed: true
copyedit: true
version: 4.1.0
last_tested: 2018-11-01
steps:
  - 
    title: Pengantar
  - 
    title: Animate a ghost
  - 
    title: Hantu acak
    completion:
      - engaged
  - 
    title: Code for catching ghosts
  - 
    title: Add a score
  - 
    title: Add a timer
    completion:
      - internal
  - 
    title: Challenge
    challenge: true
    completion:
      - external
  - 
    title: What can you do now?
