---
title: Lovci na duhove
hero_image: images/ghostbusters.png
description: Naredio igro v kateri loviš duhove!
listed: true
copyedit: true
version: 4.1.0
last_tested: 2018-11-01
steps:
  - 
    title: Uvod
  - 
    title: Animiraj duhca
  - 
    title: Naključni duhovi
    completion:
      - engaged
  - 
    title: Code for catching ghosts
  - 
    title: Add a score
  - 
    title: Add a timer
    completion:
      - internal
  - 
    title: Challenge
    challenge: true
    completion:
      - external
  - 
    title: What can you do now?
