---
title: Lovci duchů
hero_image: images/ghostbusters.png
description: Udělej hru o chytání duchů!
listed: true
copyedit: true
version: 4.1.0
last_tested: 2018-11-01
steps:
  - 
    title: Úvod
  - 
    title: Animate a ghost
  - 
    title: Náhodní duchové
    completion:
      - engaged
  - 
    title: Code for catching ghosts
  - 
    title: Add a score
  - 
    title: Add a timer
    completion:
      - internal
  - 
    title: Challenge
    challenge: true
    completion:
      - external
  - 
    title: What can you do now?
