---
title: Szellemirtók
hero_image: images/ghostbusters.png
description: Készíts játékot a szellemek elfogásáról!
listed: true
copyedit: true
version: 4.1.0
last_tested: 2018-11-01
steps:
  - 
    title: Bevezetés
  - 
    title: Animálj egy szellemet
  - 
    title: Véletlenül feltűnő szellemek
    completion:
      - engaged
  - 
    title: 'Kihívás: több véletlenszerűség'
    challenge: true
  - 
    title: A szellemek elfogásának kódja
  - 
    title: 'Kihívás: hang hozzáadása'
    challenge: true
  - 
    title: Adj hozzá egy pontszámot
  - 
    title: Időzítő hozzáadása
    completion:
      - internal
  - 
    title: 'Kihívás: többféle szereplő'
    challenge: true
  - 
    title: What next?
