---
title: SOS Fantômes
hero_image: images/ghostbusters.png
description: Faire un jeu sur l’interception des fantômes !
original_url: https://www.codeclubprojects.org/en-GB/scratch/ghostbusters
theme: vert
listed: true
copyedit: true
ingredient: false
duration: 2
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
interests: jeu
technologies: scratch
site_areas: projects
hardware: ''
software: scratch
version: 4.2
last_tested: 2018-01-01
steps:
  - 
    title: Introduction
  - 
    title: Animating a ghost
  - 
    title: Random ghosts
  - 
    title: Catching ghosts
  - 
    title: Adding a score
  - 
    title: Adding a timer
  - 
    title: 'Challenge: more objects'
