---
title: صائدو الأشباح
hero_image: images/ghostbusters.png
description: اصنع لعبة عن إصطياد الأشباح!
listed: true
copyedit: true
version: 4.1.0
last_tested: 2018-11-01
steps:
  - 
    title: المقدمة
  - 
    title: تحريك الشبح
  - 
    title: أشباح عشوائية
    completion:
      - engaged
  - 
    title: Code for catching ghosts
  - 
    title: Add a score
  - 
    title: Add a timer
    completion:
      - internal
  - 
    title: Challenge
    challenge: true
    completion:
      - external
  - 
    title: What can you do now?
