---
title: Pogromcy duchów
hero_image: images/ghostbusters.png
description: Zrób grę o łapaniu duchów!
listed: true
copyedit: true
version: 4.1.0
last_tested: 01 listopada 2018
steps:
  - 
    title: Życzenia urodzinowe
  - 
    title: Animuj ducha
  - 
    title: Losowe duchy
  - 
    title: 'Wyzwanie: większa losowość'
    challenge: true
  - 
    title: Kod do łapania duchów
  - 
    title: 'Wyzwanie: dodaj dźwięk'
    challenge: true
  - 
    title: Dodaj wynik
  - 
    title: Dodaj licznik czasu
  - 
    title: 'Wyzwanie: więcej duszków'
    challenge: true
  - 
    title: Test yourself
  - 
    title: Co dalej?
