---
title: Pogromcy duchów
hero_image: images/ghostbusters.png
description: Zrób grę o łapaniu duchów!
listed: true
copyedit: true
version: 4.1.0
last_tested: 01 listopada 2018
steps:
  - 
    title: Życzenia urodzinowe
  - 
    title: Animuj ducha
  - 
    title: Losowe duchy
    completion:
      - engaged
  - 
    title: Code for catching ghosts
  - 
    title: Add a score
  - 
    title: Add a timer
    completion:
      - internal
  - 
    title: Challenge
    challenge: true
    completion:
      - external
  - 
    title: What can you do now?
