---
title: Κυνηγοί φαντασμάτων
hero_image: images/ghostbusters.png
description: Κάνε ένα παιχνίδι για τo πιάσιμο φαντασμάτων!
listed: true
copyedit: true
version: 4.1.0
last_tested: 2018-11-01
steps:
- title: Εισαγωγή
  completion: engaged
- title: Σχεδίασε ένα φάντασμα
- title: Τυχαία φαντάσματα
- title: 'Πρόκληση: περισσότερη τυχαιότητα'
  challenge: true
- title: Κώδικας για να πιάνεις φαντάσματα
- title: 'Πρόκληση: πρόσθεσε ήχο'
  challenge: true
- title: Προσθήκη βαθμολογίας
  completion: internal
- title: Πρόσθεσε ένα χρονόμετρο
- title: 'Πρόκληση: περισσότεροι χαρακτήρες'
  challenge: true
- title: Έλεγχος γνώσεων
- title: Και τώρα;
