---
title: SOS Fantômes
hero_image: images/ghostbusters.png
description: Fais un jeu pour attraper des fantômes!
listed: true
copyedit: true
version: 4.1.0
last_tested: 2018-11-01
steps:
- title: Introduction
  completion: engaged
- title: Animer un fantôme
- title: Fantômes aléatoires
- title: 'Défi: plus aléatoire'
  challenge: true
- title: Code pour capturer les fantômes
- title: 'Défi: ajouter un son'
  challenge: true
- title: Ajouter un score
  completion: internal
- title: Ajouter un minuteur
- title: 'Défi: plus de sprites'
  challenge: true
- title: Teste-toi
- title: Et ensuite?
