---
title: Ghostbusters
hero_image: images/ghostbusters.png
description: Faites un jeu sur attraper des fantômes!
original_url: https://www.codeclubprojects.org/en-GB/scratch/ghostbusters
theme: green
listed: true
copyedit: true
ingredient: false
duration: 2
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
interests: jeux
technologies: scratch
site_areas: projets
hardware: ''
software: scratch
version: 4
last_tested: 2018-01-01
steps:
  - 
    title: Introduction
  - 
    title: Ce dont tu auras besoin
  - 
    title: Animer un fantôme
  - 
    title: Fantômes aléatoires
  - 
    title: Ajouter le pointage
  - 
    title: Ajouter un compte à rebours
  - 
    title: 'Défi: Plus d''objets'
  - 
    title: 'Défi : plus d''objets'
