---
title: Hayalet Avcıları
hero_image: images / ghostbusters.png
description: Hayaletleri yakalama oyunu yapın!
original_url: https://www.codeclubprojects.org/en-GB/scratch/ghostbusters
theme: yeşil
listed: true
copyedit: true
ingredient: false
duration: 2
curriculum: 1, tasarım-0, programlama-1, phys-comp-0, üretim-0, topluluk-0
interests: oyunlar
technologies: çizik
site_areas: projeler
hardware: ''
software: çizik
version: 4.2.1
last_tested: 2018-01-01
steps:
  - 
    title: Giriş
  - 
    title: Bir hayaletin animasyonu
  - 
    title: Rastgele hayaletler
  - 
    title: Hayaletleri yakalamak
  - 
    title: Puantör eklemek
  - 
    title: Süre eklemek
  - 
    title: 'Meydan Okuma: Daha fazla nesne'
    challenge: true
